// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/2/2024, 9:07:02 PM
const configMerger = require("/home/myurioka/myurioka.github.io/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/myurioka/myurioka.github.io/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/myurioka/myurioka.github.io/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/myurioka/myurioka.github.io/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/myurioka/myurioka.github.io/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/myurioka/myurioka.github.io/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/myurioka/myurioka.github.io/plugins/**/*.{js,ts,mjs}","/home/myurioka/myurioka.github.io/composables/**/*.{js,ts,mjs}","/home/myurioka/myurioka.github.io/utils/**/*.{js,ts,mjs}","/home/myurioka/myurioka.github.io/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/myurioka/myurioka.github.io/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/myurioka/myurioka.github.io/app.config.{js,ts,mjs}"] }));

module.exports = config
